FROM    aadebuger/pythonflask
#run pip install pingpp
#run pip install flask
#run pip install pymongo
#run pip install mongoengine
#run pip install flask_restful
#run pip install passlib
run pip install qiniu
run pip install passlib
run pip install pybuilder
run pip install flake8
add  build.py /code1
run mkidr /code1/src/main
add  src/main/ /code1/src/main
EXPOSE 5000
workdir /code1/
run pyb package
#CMD ["python", "jetcloud/jetcloudrest.py"]
