FROM    aadebuger/pythonflask
Add src/main/python /code
#run pip install pingpp
#run pip install flask
#run pip install pymongo
#run pip install mongoengine
#run pip install flask_restful
#run pip install passlib
run pip install qiniu
run pip install passlib
EXPOSE 5000
workdir /code
CMD ["python", "jetcloud/jetcloudrest.py","core"]
