#FROM    python:2
FROM    aadebuger/pythonflask
#run pip install pingpp
#run pip install flask
#run pip install pymongo
#run pip install mongoengine
#run pip install flask_restful
run pip install passlib
run pip install leancloud-sdk
#run pip install  Celery
Add src/main/python/ /code
EXPOSE 8888
workdir /code
CMD ["python", "jetcloud/pay.py"]
